apiVersion:  apps/v1
kind: ReplicaSet
metadata:
  name: go-demo-2
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      service: go-demo-2
  template:
    metadata:
      labels:
        type: backend
        service: go-demo-2
        db: mongo
        language: go
    spec:
      containers:
      - name: db
        image: mongo:7.0
      - name: api
        image: nginx:alpine
        env:
        - name: DB
          value: localhost
        # livenessProbe:
        #   httpGet:
        #     path: /demo/hello
        #     port: 8080
        #   initialDelaySeconds: 15  # <--- Agrega esto: espera 15 seg antes del primer chequeo
        #   periodSeconds: 10
